import type { DeviceColorVariant, DeviceDefinition } from '@/lib/types'

const APPLE_VARIANTS: DeviceColorVariant[] = [
  { id: 'black', name: 'Black Titanium', body: '#1c1c1e', edge: '#3a3a3c' },
  { id: 'natural', name: 'Natural Titanium', body: '#8a8a8e', edge: '#b8b8bd' },
  { id: 'white', name: 'White Titanium', body: '#e7e7e9', edge: '#c8c8cc' },
  { id: 'blue', name: 'Blue Titanium', body: '#3b4a5a', edge: '#5c6f80' },
]

const ANDROID_VARIANTS: DeviceColorVariant[] = [
  { id: 'black', name: 'Obsidian', body: '#202124', edge: '#3c4043' },
  { id: 'porcelain', name: 'Porcelain', body: '#e8e6e1', edge: '#cdcac3' },
  { id: 'mint', name: 'Mint', body: '#9fc6b8', edge: '#bcd9cf' },
]

export const DEVICES: DeviceDefinition[] = [
  {
    id: 'iphone-16-pro-max',
    name: 'iPhone 16 Pro Max',
    platform: 'apple',
    frameWidth: 322,
    frameHeight: 660,
    screenX: 16,
    screenY: 16,
    screenWidth: 290,
    screenHeight: 628,
    frameColor: '#1c1c1e',
    bodyRadius: 64,
    screenRadius: 52,
    notch: 'island',
    colorVariants: APPLE_VARIANTS,
  },
  {
    id: 'iphone-16-pro',
    name: 'iPhone 16 Pro',
    platform: 'apple',
    frameWidth: 300,
    frameHeight: 620,
    screenX: 15,
    screenY: 15,
    screenWidth: 270,
    screenHeight: 590,
    frameColor: '#1c1c1e',
    bodyRadius: 60,
    screenRadius: 48,
    notch: 'island',
    colorVariants: APPLE_VARIANTS,
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    platform: 'apple',
    frameWidth: 292,
    frameHeight: 600,
    screenX: 15,
    screenY: 15,
    screenWidth: 262,
    screenHeight: 570,
    frameColor: '#2c2c2e',
    bodyRadius: 58,
    screenRadius: 46,
    notch: 'island',
    colorVariants: APPLE_VARIANTS,
  },
  {
    id: 'iphone-14',
    name: 'iPhone 14',
    platform: 'apple',
    frameWidth: 292,
    frameHeight: 600,
    screenX: 15,
    screenY: 15,
    screenWidth: 262,
    screenHeight: 570,
    frameColor: '#3a3a3c',
    bodyRadius: 56,
    screenRadius: 44,
    notch: 'notch',
    colorVariants: APPLE_VARIANTS,
  },
  {
    id: 'ipad-pro',
    name: 'iPad Pro',
    platform: 'apple',
    frameWidth: 480,
    frameHeight: 640,
    screenX: 22,
    screenY: 22,
    screenWidth: 436,
    screenHeight: 596,
    frameColor: '#1c1c1e',
    bodyRadius: 40,
    screenRadius: 24,
    notch: 'none',
    colorVariants: APPLE_VARIANTS,
  },
  {
    id: 'pixel-9',
    name: 'Pixel 9',
    platform: 'android',
    frameWidth: 300,
    frameHeight: 620,
    screenX: 14,
    screenY: 14,
    screenWidth: 272,
    screenHeight: 592,
    frameColor: '#202124',
    bodyRadius: 52,
    screenRadius: 40,
    notch: 'punch-hole',
    colorVariants: ANDROID_VARIANTS,
  },
  {
    id: 'pixel-8',
    name: 'Pixel 8',
    platform: 'android',
    frameWidth: 292,
    frameHeight: 600,
    screenX: 14,
    screenY: 14,
    screenWidth: 264,
    screenHeight: 572,
    frameColor: '#303134',
    bodyRadius: 50,
    screenRadius: 38,
    notch: 'punch-hole',
    colorVariants: ANDROID_VARIANTS,
  },
  {
    id: 'galaxy-s25',
    name: 'Galaxy S25',
    platform: 'android',
    frameWidth: 296,
    frameHeight: 620,
    screenX: 12,
    screenY: 12,
    screenWidth: 272,
    screenHeight: 596,
    frameColor: '#111111',
    bodyRadius: 44,
    screenRadius: 34,
    notch: 'punch-hole',
    colorVariants: ANDROID_VARIANTS,
  },
]

export function getDevice(id: string): DeviceDefinition | undefined {
  return DEVICES.find((device) => device.id === id)
}

export function getDeviceVariant(
  device: DeviceDefinition,
  variantId?: string,
): DeviceColorVariant {
  return (
    device.colorVariants.find((variant) => variant.id === variantId) ??
    device.colorVariants[0]
  )
}
